apiVersion: batch/v1
kind: Job
metadata:
  name: k8s-update-deployment-ecr-tag-setup
  namespace: kube-system
spec:
  template:
    spec:
      serviceAccountName: k8s-update-deployment-ecr-tag
      containers:
      - name: k8s-update-deployment-ecr-tag-setup
        # This is a minimal kubectl image based on Alpine Linux that signs certificates using the k8s extension api server
        image: leminou/k8s-webhook-cert-manager:v1.0.1
        command: ["./generate_certificate.sh"]
        args:
          - "--service"
          - "k8s-update-deployment-ecr-tag"
          - "--webhook"
          - "k8s-update-deployment-ecr-tag.brilliantsolutions.com"
          - "--secret"
          - "k8s-update-deployment-ecr-tag-secret"
          - "--namespace"
          - "kube-system"
      restartPolicy: OnFailure
  backoffLimit: 3