apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: k8s-update-deployment-ecr-tag-cluster-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: k8s-update-deployment-ecr-tag-cluster-role
subjects:
  - kind: ServiceAccount
    name: k8s-update-deployment-ecr-tag
    namespace: kube-system
