apiVersion: v1
kind: Service
metadata:
  name: k8s-update-deployment-ecr-tag
  namespace: kube-system
spec:
  type: ClusterIP
  selector:
    app: k8s-update-deployment-ecr-tag
  ports:
    - protocol: TCP
      port: 443
      targetPort: 8000
