apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: "k8s-update-deployment-ecr-tag.brilliantsolutions.com"
  namespace: kube-system
webhooks:
  - name: "k8s-update-deployment-ecr-tag.brilliantsolutions.com"
  # this will be removed once deployement of webhook and its components compelete
    objectSelector:
      matchLabels:
        stop-from-executing: "true"
    rules:
      - apiGroups: ["apps"]
        apiVersions: ["v1"]
        operations: ["CREATE", "UPDATE"]
        resources: ["deployments"]
        scope: "Namespaced"
    clientConfig:
      service:
        namespace: "kube-system"
        name: "k8s-update-deployment-ecr-tag"
        path: /
    admissionReviewVersions: ["v1"]
    sideEffects: None
    timeoutSeconds: 10
