apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: "k8s-update-deployment-ecr-tag.smartdev.ai"
  namespace: kube-system
webhooks:
  - name: "k8s-update-deployment-ecr-tag.smartdev.ai"
    objectSelector:
      matchLabels:
        hello: "true"
    rules:
      - apiGroups: [""]
        apiVersions: ["v1"]
        operations: ["CREATE", "UPDATE"]
        resources: ["pods"]
        scope: "Namespaced"
    clientConfig:
      service:
        namespace: "kube-system"
        name: "k8s-update-deployment-ecr-tag"
        path: /
    admissionReviewVersions: ["v1", "v1beta1"]
    sideEffects: None
    timeoutSeconds: 10
