apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-update-deployment-ecr-tag
  namespace: kube-system
  labels:
    app: k8s-update-deployment-ecr-tag
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8s-update-deployment-ecr-tag
  template:
    metadata:
      labels:
        app: k8s-update-deployment-ecr-tag
    spec:
      containers:
        - name: k8s-update-deployment-ecr-tag
          image: CONTAINER_IMAGE
          ports:
            - containerPort: 8000
          volumeMounts:
            - name: k8s-update-deployment-ecr-tag-secret
              mountPath: "/tls"
              readOnly: true
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          env:
            - name: DEPLOYMENT_NAMESPACE
              value: release
            - name: AWS_DEFAULT_REGION
              value: eu-west-3

      volumes:
        - name: k8s-update-deployment-ecr-tag-secret
          secret:
            secretName: k8s-update-deployment-ecr-tag-secret
