resources:
- deployment.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: CONTAINER_IMAGE
  newName: 174391158959.dkr.ecr.eu-west-3.amazonaws.com/k8s-update-deployment-ecr-tag
  newTag: 1.0.6
